### ISSUE TITLE
推荐整个教程放README.md

### ISSUE THREAD

**Issue by 3360891395** [kukume/kukubot#29]
我是之前你的某个无名群员，苦于你的博客无法访问经常无法搭建稳定的bot

**Comment by kukume** [comment]
现在应该能正常访问了。cdn抽风了。我可能会考虑不用cdn。

**Comment by Cubik65536** [comment]
我这边（kuku-bot新下游）倒是有可能搭一个kuku-bot专用文档站

**Comment by kukume** [comment]
@Cubik65536 感谢大佬，别有可能了，直接搭一个

**Comment by Cubik65536** [comment]
> @Cubik65536 感谢大佬，别有可能了，直接搭一个

@kukume 等我把我这边的kkb下游写完（

**Comment by kukume** [comment]
已贴出Windows搭建文档~~

**Comment by Cubik65536** [comment]
~~看来我咕的还是太狠了~~
