### ISSUE TITLE
kukubot的功能打不开

### ISSUE THREAD

**Issue by 12123ads** [kukume/kukubot#46]
![image](https://user-images.githubusercontent.com/69107029/120643176-67cd7500-c4a8-11eb-976f-283f71e35b80.png)
这些功能都打不开

**Comment by Cubik65536** [comment]
kukubot文档正在撰写，在此之前请参考以下指引：

开关命令为：
- kukubot {status}
- loc监控 {status}
- 整点报时 {status}
- 自动审核 {status}
- 欢迎语 {status}
- 退群拉黑 {status}
- 鉴黄 {status}
- 色图 {status}
- 撤回通知 {status}
- 闪照通知 {status}
- 复读 {status}
- 语音识别 {status}
- 进群未发言踢出 {status}

如需打开/关闭功能，输入命令并将{status}替换为 `开`/`关`

**不需要加入kukubot前缀，否则只会关闭机器人**

**Comment by 12123ads** [comment]
好的
