### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by KKKKeybird** [kukume/kukubot#49]
能不能加个图灵机器人api的聊天ai功能啊

**Comment by kukume** [comment]
没有免费的？

**Comment by Cubik65536** [comment]
> 没有免费的？

有，我加了，你删了

**Comment by Cubik65536** [comment]
> 没有免费的？

有，而且我提交过，但是在你弄Controller的时候似乎没有把我的功能写回去

**Comment by KKKKeybird** [comment]
> 没有免费的？

以前好像有的，现在没了

**Comment by kukume** [comment]
私聊机器人
`图灵 apikey userid`
然后再群里艾特机器人，就会使用图灵的api
