### ISSUE TITLE
请问一下哔哩哔哩的开播提醒能否做一个群提醒的的功能而不是私聊提醒

### ISSUE THREAD

**Issue by LemonPAKA** [kukume/kukubot#50]
加哔哩哔哩监控 这个命令只会监控动态以及投稿的视频（也算动态），但是开播不会提醒

**Comment by LemonPAKA** [comment]
另外就是加拦截指令之后，我作为机器人主人发出指令也无效

**Comment by kukume** [comment]
我记得加拦截  是不拦截主人的

**Comment by LemonPAKA** [comment]
> 我记得加拦截 是不拦截主人的

但是我加拦截 查撤回之后，我发查撤回也没反应，给的超管查也没反应

**Comment by kukume** [comment]
https://github.com/kukume/kukubot/releases/tag/0.0.3
你可以试试。

**Comment by LemonPAKA** [comment]
> https://github.com/kukume/kukubot/releases/tag/0.0.3
> 你可以试试。

是直接换掉原来的jar吗，应该能继承老数据吧？

**Comment by kukume** [comment]
不能继承老数据。。 
这个基于另一个框架写的

**Comment by LemonPAKA** [comment]
> 不能继承老数据。。 这个基于另一个框架写的

那之前的存的问答又要重新存一遍咯orz,对了,就加问答的功能,能不能做一个私聊控制
比如私聊 加问答 问题内容 匹配类型(可选) Q群(可选),Q群不填写的话就是所有已加入的群都会启用,填写了Q群就仅限某个群
另外就是同关键词的问答能够开启随机回答功能,有时候想弄些整活回答弄个不了随机有点难受

**Comment by kukume** [comment]
问答有多个默认随机回复，私聊加问答已实现
yuq的数据库我也照着  simbot版的来写了。所以数据库你想继承simbot的数据库的话
在conf目录下新建一个db.properties，填入
```
db.url=jdbc:h2:./db/simbot
db.username=simbot
```

**Comment by kukume** [comment]
simbot的消息id是字符串。。yuq的消息id是数字

**Comment by LemonPAKA** [comment]
> simbot的消息id是字符串。。yuq的消息id是数字

加问答报错，我用的是新生成的数据库

**Comment by kukume** [comment]
这个等会发包。暂时只能纯文字
