### ISSUE TITLE
舔狗日记功能的api换了

### ISSUE THREAD

**Issue by lkiuyu** [kukume/kukubot#51]
api更换了，使用舔狗日记提示更换v2接口

**Comment by kukume** [comment]
这个api的v2接口是收费的。。。。。

**Comment by lkiuyu** [comment]
> 这个api的v2接口是收费的。。。。。

试试这个里面的api能用吗https://api.oick.cn/
在百度搜索到的

**Comment by kukume** [comment]
能用。

**Comment by kukume** [comment]
如果你不在意数据  以及 群管功能，可以使用https://github.com/kukume/kukubot/releases/tag/0.0.1
yuq的db有bug，我想等db的bug修复之后再改
