### ISSUE TITLE
希望加个github监控的功能

### ISSUE THREAD

**Issue by 12123ads** [kukume/kukubot#54]
就是github的仓库的活动都转发到QQ群

**Comment by Cubik65536** [comment]
Working on it on `simbot` branch, but it depends on @kukume to accept it or not

------

I will probably finish it in early august.

**Comment by kukume** [comment]
是issues的提醒？

**Comment by Cubik65536** [comment]
> 是issues的提醒？

应该是新commit，issue和pull request都能提醒

**Comment by 12123ads** [comment]
嗯


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月26日(周一) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kukume/kukubot] 希望加个github监控的功能 (#54)




  
是issues的提醒？
  
应该是新commit，issue和pull request都能提醒
 
&mdash;

**Comment by kukume** [comment]
> > 是issues的提醒？
> 
> 应该是新commit，issue和pull request都能提醒

有api吗？

**Comment by 12123ads** [comment]
最好加个开关是否推送新commit，issue和pull request

**Comment by Cubik65536** [comment]
> > > 是issues的提醒？
> 
> > 
> 
> > 应该是新commit，issue和pull request都能提醒
> 
> 
> 
> 有api吗？

GitHub API已经提供相应方法，实际上就是触发webhook向指定地址发送POST请求，弄出一个web controller再为GitHub做下解析就行

**Comment by kukume** [comment]
api地址 或者文档有吗？

**Comment by kukume** [comment]
不用了，我看到了

**Comment by kukume** [comment]
github的webhook  填写
http://IP:8081/github-webhook
然后再需要推送的群内发送 
github监控 开
