### ISSUE TITLE
色图功能开关检测有问题

### ISSUE THREAD

**Issue by LemonPAKA** [kukume/kukubot#56]
![image](https://user-images.githubusercontent.com/17202894/128775301-fb285778-1229-431b-9598-37242359582f.png)
如图

**Comment by Cubik65536** [comment]
首先 `色图十连` 才是真正的命令，使用 `色图10连` 会导致解析错误。另外，由于 `色图10连` 带来的解析错误导致色图功能被关闭，所以 `色图` 命令也会失效。注意，跟随 `色图` 命令的提示为：”色图功能已关闭” 而非 “色图关闭成功”。

**Comment by LemonPAKA** [comment]
> 首先 `色图十连` 才是真正的命令，使用 `色图10连` 会导致解析错误。另外，由于 `色图10连` 带来的解析错误导致色图功能被关闭，所以 `色图` 命令也会失效。注意，跟随 `色图` 命令的提示为：”色图功能已关闭” 而非 “色图关闭成功”。
> 
> `色图切换` 功能似乎已失效

![Screenshot_2021-08-10-06-44-33-092_com tencent mo](https://user-images.githubusercontent.com/17202894/128783587-a5b597d7-c682-4274-b783-88fb3a41414d.jpg)
色图十连也是一样的

**Comment by kukume** [comment]
没有切换功能了，直接使用我的api
