### ISSUE TITLE
建议将查问答与删问答也加入私聊机制,同时为加问答增加取消(或者返回上一步)机制

### ISSUE THREAD

**Issue by LemonPAKA** [kukume/kukubot#60]
如题,加问答有时候不小心输入错误关键词名或者选择错匹配机制,必须要完全添加,并且去到响应群里才能够删除,若是群聊提交多,并且添加了所有群,就必须去每一个群都删除,过于繁琐
还有就是机器人命令中的 百度 xxxxx 返回的域名打开跳转之后提示static.kukuqaq.com无法访问

**Comment by LemonPAKA** [comment]
对了，群哔哩哔哩的动态监控和直播监控能否增加艾特全员的选项（当然是仅在BOT是管理员的情况下可用）

**Comment by kukume** [comment]
无法访问，域名有问题，暂时无法解决
问答 取消，30s没有回复就取消了

**Comment by LemonPAKA** [comment]
> 无法访问，域名有问题，暂时无法解决
> 问答 取消，30s没有回复就取消了

所以就是我写了加问答 关键词
然后30s内没给机器人回复自动取消对吧，还是？

**Comment by kukume** [comment]
30s没回复&nbsp; 控制台会抛个异常&nbsp; 就等于取消了

**Comment by LemonPAKA** [comment]
> 30s没回复&nbsp; 控制台会抛个异常&nbsp; 就等于取消了

 问答的随机返图貌似有点问题，我设置了两个”还不睡觉“的问答（模糊匹配），然后只会出现新加的那个问答的图

**Comment by kukume** [comment]
![H4HAXC)ORCB I68T5UYH)XH](https://user-images.githubusercontent.com/45278810/132045149-1375c39b-a16f-4475-8bae-f04d32fb5f33.png)

测试并没有问题

**Comment by LemonPAKA** [comment]
> ![H4HAXC)ORCB I68T5UYH)XH](https://user-images.githubusercontent.com/45278810/132045149-1375c39b-a16f-4475-8bae-f04d32fb5f33.png)
> 
> 测试并没有问题

很好奇它的随机逻辑。。感觉一个时间段内发的话都会是同一张图orz

**Comment by kukume** [comment]
把符合匹配的答案拿出来，随机挑一个

**Comment by kukume** [comment]
私聊：
`删问答 {q} {group}`
`查问答 {group}`
网站能正常打开了
