### ISSUE TITLE
不能发送图片

### ISSUE THREAD

**Issue by fzs3** [kukume/kukubot#61]
撤回图片的提示和色图，都没有发送出来，控制台没有异常输出。这是框架问题吗。

**Comment by kukume** [comment]
https://pan.kuku.me/kukubot/   是这里的版本吗  我测试是可以发的

**Comment by fzs3** [comment]
不是这个，是 sim 版本！

**Comment by kukume** [comment]
https://pan.kuku.me/kukubot/simbot/   
更新一下

**Comment by fzs3** [comment]
OK,完美解决！
